zh:
  guide:
    - title: 指南
      name: Guide
      items:
        - title: 介绍
          name: Introduction
        - title: 安装
          name: Installation
        - title: 快速上手
          name: Quickstart
  components:
    - title: API
      name: Docs
      items:
        - title: OD图/ODLayer
          name: ODAPI
        - title: 点图/PointLayer
          name: PointAPI
        - title: 标记图/MarkerLayer
          name: MarkerAPI
        - title: 多边形图/PolygonLayer
          name: PolygonAPI
        - title: 线图/PolylineLayer
          name: PolylineAPI
        - title: Canvas线图/CanvasPolylineLayer
          name: CanvasPolylineAPI
        - title: Canvas方格图/CanvasGridLayer
          name: CanvasGridAPI
        - title: 基类/BaseLayer
          name: BaseAPI
        - title: 集合图层/GroupLayer
          name: GroupAPI
        - title: 热力图/Heatmap
          name: HeatMapAPI
        - title: GeoJSON图/GeoJson
          name: GeoJsonAPI
        - title: 时间轴图层/TimelineLayer
          name: TimelineAPI
  demo:
    - title: 演示
      name: Demo
      items:
        - title: 全部
          name: demos
  about:
    - title: 关于我们
      name: About
      items:
        - title: 团队介绍
          name: Us
     
en:
  guide:
    - title: Guide
      name: Guide
      items:
        - title: DMap Introduction
          name: Introduction
        # - title: 安装
        #   name: Installation
        # - title: 快速上手
        #   name: Quickstart
  components:
    - title: API
      name: Docs
      items:
        # - title: OD图/ODLayer
        #   name: ODAPI
        - title: PointLayer
          name: PointAPI
        - title: MarkerLayer
          name: MarkerAPI
        - title: PolygonLayer
          name: PolygonAPI
        - title: PolylineLayer
          name: PolylineAPI
        - title: CanvasPolylineLayer
          name: CanvasPolylineAPI
        - title: CanvasGridLayer
          name: CanvasGridAPI
        - title: BaseLayer
          name: BaseAPI
        - title: GroupLayer
          name: GroupAPI
        # - title: 热力图/Heatmap
        #   name: HeatMapAPI
        # - title: GeoJSON图/GeoJson
        #   name: GeoJsonAPI
        # - title: 时间轴图层/TimelineLayer
        #   name: TimelineAPI
  demo:
    - title: Demo
      name: Demo
      items:
        - title: All
          name: demos
  # about:
  #   - title: 关于我们
  #     name: About
  #     items:
    #     - title: 团队介绍
    #       name: Us
