zh:
  guide:
    - title: 指南
      name: Guide
      items:
        - title: 介绍
          name: Introduction
        - title: 安装
          name: Installation
        - title: 快速上手
          name: Quickstart
    # - title: 地图组件
    #   name: Docs
  components:
    - title: API
      name: Docs
      items:
        - title: OD图/ODLayer
          name: ODAPI
        - title: 点图/PointLayer
          name: PointAPI
        - title: 标记图/MarkerLayer
          name: MarkerAPI
        - title: 多边形图/PolygonLayer
          name: PolygonAPI
        - title: 线图/PolylineLayer
          name: PolylineAPI
        - title: Canvas线图/CanvasPolylineLayer
          name: CanvasPolylineAPI
        - title: Canvas方格图/CanvasGridLayer
          name: CanvasGridAPI
        - title: 基类/BaseLayer
          name: BaseAPI
        - title: 集合图层/GroupLayer
          name: GroupAPI
  demo:
    - title: 演示
      name: Demo
      items:
        - title: 全部
          name: demos
     
en:
  guide:
    - title: Brand
      name: Guide
      items:
        - title: Color
          name: Color
        - title: Typography
          name: Typography
  resource:
    - title: Resource
      name: Resource
      items:
        - title: Design
          name: design
  components:
    - title: Overview
      name: Docs
      items:
        - title: Introduction
          name: Introduction
        - title: Installation
          name: Installation
        - title: Quickstart
          name: Quickstart
        - title: Internationalization
          name: i18n
        - title: Change Log
          name: Changelog
    - title: Components
      name: Docs
      groups:
        - title: Base
          items:
            - title: Button
              name: Button
            - title: Layout
              name: Layout
            - title: Tag
              name: Tag
            - title: Icon
              name: Icon
        - title: Form
          items:
            - title: Checkbox
              name: Checkbox
            - title: Input
              name: Input
            - title: InputNumber
              name: InputNumber
            - title: Radio
              name: Radio
            - title: Rate
              name: Rate
            - title: Select
              name: Select
            - title: Switch
              name: Switch
            - title: Slider
              name: Slider
            - title: Textarea
              name: Textarea
        - title: View
          items:
            - title: Alert
              name: Alert
            - title: Badge
              name: Badge
            - title: Card
              name: Card
            - title: Collapse
              name: Collapse
            - title: LoadingBar
              name: LoadingBar
            - title: Modal
              name: Modal
            - title: Message
              name: Message
            - title: Notification
              name: Notification
            - title: Popover
              name: Popover
            - title: Progress
              name: Progress
            - title: Timeline
              name: Timeline
            - title: Tooltip
              name: Tooltip
            - title: Table
              name: Table
        - title: Navigation
          items:
            - title: Breadcrumb
              name: Breadcrumb
            - title: Dropdown
              name: Dropdown
            - title: Menu
              name: Menu
            - title: Pagination
              name: Pagination
            - title: Steps
              name: Steps
            - title: Tabs
              name: Tabs
